version: "3.1"

services:
  drupal:
    image: drupal:9-apache
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
    depends_on:
      - postgres
    networks:
      - app-net

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    networks:
      - app-net
    volumes:
      - drupal-vol:/var/lib/postgresql/data

networks:
  app-net:

volumes:
  drupal-vol:
